FATAL_ERRORS_PER_MINUTE_THRESHOLD = 10
FATAL_ERRORS_PER_HOUR_THRESHOLD = 10

MINUTE_WINDOW = "min"
HOUR_WINDOW = "h"

DATA_DIR = "./data"
LOG_FILE_PATTERN = "data.csv"

ENABLE_CATEGORY_OPTIMIZATION = True
ENABLE_DATETIME_OPTIMIZATION = True
ENABLE_NUMERIC_DOWNCASTING = True
