USE SCHEMA AIRLINE_DWH.CORE_DWH;

ALTER VIEW SECURE_FACT_FLIGHTS 
DROP ROW ACCESS POLICY admin_only_policy;
CREATE OR REPLACE ROW ACCESS POLICY admin_only_policy 
AS (val STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() = 'ACCOUNTADMIN';
ALTER VIEW SECURE_FACT_FLIGHTS 
ADD ROW ACCESS POLICY admin_only_policy ON (passenger_status);

CREATE OR REPLACE SECURE VIEW SECURE_FACT_FLIGHTS AS 
SELECT 
    F.flight_id,
    F.departure_date,
    I.passenger_status,
    I.ticket_type,
    F.loaded_at
FROM AIRLINE_DWH.CORE_DWH.FACT_FLIGHTS F
JOIN AIRLINE_DWH.CORE_DWH.DIM_FLIGHT_INFO I ON F.info_sk = I.info_sk;

ALTER VIEW SECURE_FACT_FLIGHTS 
ADD ROW ACCESS POLICY admin_only_policy ON (passenger_status);

SELECT * FROM SECURE_FACT_FLIGHTS LIMIT 10;