USE SCHEMA AIRLINE_DWH.CORE_DWH;
SELECT * FROM DIM_PASSENGER AT(OFFSET => -60*2);
UPDATE DIM_PASSENGER SET age = age + 1 WHERE passenger_sk = 1;
SELECT * FROM DIM_PASSENGER AT(TIMESTAMP => DATEADD(minute, -1, CURRENT_TIMESTAMP()));
CREATE OR REPLACE TABLE FACT_FLIGHTS_BACKUP CLONE FACT_FLIGHTS AT(OFFSET => -60*5);
DROP TABLE FACT_FLIGHTS_BACKUP;
UNDROP TABLE FACT_FLIGHTS_BACKUP;